# -*- coding: utf-8 -*-
import os

import requests
# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_uploadDialog(object):
    def __init__(self):
        self.file_path = None

    def setupUi(self, uploadDialog):
        uploadDialog.setObjectName("uploadDialog")
        uploadDialog.resize(428, 200)
        self.horizontalLayout = QtWidgets.QHBoxLayout(uploadDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.uploadStateLabel = QtWidgets.QLabel(uploadDialog)
        self.uploadStateLabel.setText("")
        self.uploadStateLabel.setObjectName("uploadStateLabel")
        self.verticalLayout.addWidget(self.uploadStateLabel)
        self.uploadProgressBar = QtWidgets.QProgressBar(uploadDialog)
        self.uploadProgressBar.setProperty("value", 0)
        self.uploadProgressBar.setObjectName("uploadProgressBar")
        self.verticalLayout.addWidget(self.uploadProgressBar)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(uploadDialog)
        QtCore.QMetaObject.connectSlotsByName(uploadDialog)

    def setUploadStateLabel(self, text):
        self.uploadStateLabel.setText(text)

    def setUploadProgressBar(self, value):
        self.uploadProgressBar.setValue(value)

    def upload_file(self, url, file_path):
        chunk_size = 1024 * 1024  # 分片大小，这里设置为 1MB
        total_size = os.path.getsize(file_path)
        total_chunks = (total_size // chunk_size) + 1

        with open(file_path, 'rb') as file:
            for chunk_number in range(total_chunks):
                start_byte = chunk_number * chunk_size
                end_byte = min((chunk_number + 1) * chunk_size, total_size)
                chunk_data = file.read(end_byte - start_byte)

                files = {
                    'file': (file_path.split('/')[-1], chunk_data),
                }

                params = {
                    'filename': file_path.split('/')[-1],
                    'chunk_number': chunk_number,
                    'total_chunks': total_chunks,
                }

                response = requests.post(url, files=files, data=params)

                if response.status_code != 200:
                    print(f"上传分片 {chunk_number} 失败")
                    self.setUploadStateLabel("上传失败")
                    return False
                else:
                    print(f"上传分片 {chunk_number} 成功")
                    self.setUploadStateLabel("上传中……请耐心等待")
                    self.setUploadProgressBar(chunk_number / total_chunks * 100)

        # 通知上传完成
        params = {
            'filename': file_path.split('/')[-1],
            'total_chunks': total_chunks,
        }
        response = requests.get(url, params=params)
        if response.status_code == 200 and response.json()['errno'] == 200:
            print("通知上传完成成功")
            self.setUploadStateLabel("上传完成!")
            self.setUploadProgressBar(100)
            return True

        print("通知上传完成失败")
        return False


    def retranslateUi(self, uploadDialog):
        _translate = QtCore.QCoreApplication.translate
        uploadDialog.setWindowTitle(_translate("uploadDialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    uploadDialog = QtWidgets.QDialog()
    ui = Ui_uploadDialog()
    ui.setupUi(uploadDialog)
    uploadDialog.show()
    sys.exit(app.exec_())
