# -*- coding: utf-8 -*-
import os

import requests
# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UI.progressDialog import Ui_progressDialog


class UploadThread(QtCore.QThread):
    progress_update = QtCore.pyqtSignal(float)

    def __init__(self, file_path, url):
        super().__init__()
        self.file_path = file_path
        self.url = url

    def run(self):
        if self.file_path is None or os.path.exists(self.file_path) is False:
            return False
        chunk_size = 1024 * 1024  # 分片大小，这里设置为 1MB
        total_size = os.path.getsize(self.file_path)
        total_chunks = (total_size // chunk_size) + 1

        with open(self.file_path, 'rb') as file:
            for chunk_number in range(total_chunks):
                start_byte = chunk_number * chunk_size
                end_byte = min((chunk_number + 1) * chunk_size, total_size)
                chunk_data = file.read(end_byte - start_byte)

                files = {
                    'file': (self.file_path.split('/')[-1], chunk_data),
                }

                params = {
                    'filename': self.file_path.split('/')[-1],
                    'chunk_number': chunk_number,
                    'total_chunks': total_chunks,
                }

                response = requests.post(self.url, files=files, data=params)

                if response.status_code != 200:
                    print(f"上传分片 {chunk_number} 失败")
                    self.progress_update.emit(-1)
                    # self.setLabel("上传失败")
                else:
                    print(f"上传分片 {chunk_number} 成功")
                    to_emit = min(chunk_number / total_chunks * 100, 99.99)
                    self.progress_update.emit(to_emit)
                    # self.setLabel("上传中……请耐心等待")
                    # self.setProgressBar(chunk_number / total_chunks * 100)

        # 通知上传完成
        params = {
            'filename': self.file_path.split('/')[-1],
            'total_chunks': total_chunks,
        }
        response = requests.get(self.url, params=params)
        if response.status_code == 200 and response.json()['errno'] == 200:
            print("通知上传完成成功")
            self.progress_update.emit(100)
            # self.setLabel("上传完成!")
            # self.setProgressBar(100)

        else:
            print("通知上传完成失败")
            self.progress_update.emit(-1)


class UploadDialog(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.thread = None
        self.ui = Ui_progressDialog()
        self.ui.setupUi(self)

    def start_upload(self, file_path, url):
        self.thread = UploadThread(file_path, url)
        self.thread.progress_update.connect(self.update_progress)
        self.thread.finished.connect(self.upload_finished)
        self.thread.start()
    
    def update_progress(self, value):
        if value == -1:
            self.ui.setLabel("上传失败")
        elif value == 100:
            self.ui.setLabel("上传完成!")
            self.ui.setProgressBar(100)
        else:
            self.ui.setLabel("上传中……请耐心等待")
            self.ui.setProgressBar(value)

    def upload_finished(self):
        print("Upload finished")

